id: P004261
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W29621
  title: ལྟ་བའི་བརྗེད་བྱང་ཆེན་མོ
  author: ''
  volumes:
    3f6266832cb747a8b50adf1aac0285a1:
      image_group_id: I1PD27416
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
