id: I47678AE1
legacy_id: P004261
ocr_import_info:
  bdrc_scan_id: W29621
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:57:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T13:56:29.661947+00:00'
last_modified: 2022-09-02 21:56:44.508382
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29621
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29621
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྟ་བའི་བརྗེད་བྱང་ཆེན་མོ།
  author: རོང་ཟོམ་པཎྜི་ཏ།
statistics:
  ocr_word_mean_confidence_index: 0.5600841376783897
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I1PD27416:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD27416
      total_pages: 50
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD27416.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5600841376783897
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
